#!/usr/bin/env node
// Builds the SVG diagrams used in the DSA notes into public/images/dsa/ and
// writes their sizes to src/data/diagramSizes.ts, so pages can reserve space
// before an image loads. Run with: npm run diagrams
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { svg } from './svg.mjs';
import { foundations } from './foundations.mjs';
import { structures } from './structures.mjs';
import { trees } from './trees.mjs';
import { graphs } from './graphs.mjs';
import { paradigms } from './paradigms.mjs';

const OUT = new URL('../../public/images/dsa/', import.meta.url);
const SIZES = new URL('../../src/data/diagramSizes.ts', import.meta.url);

const all = [...foundations, ...structures, ...trees, ...graphs, ...paradigms];

const names = new Set();
for (const d of all) {
  if (names.has(d.name)) throw new Error(`Duplicate diagram name: ${d.name}`);
  names.add(d.name);
}

await mkdir(OUT, { recursive: true });
for (const file of await readdir(OUT)) {
  if (file.endsWith('.svg') && !names.has(file.slice(0, -4))) await rm(new URL(file, OUT));
}
for (const d of all) {
  await writeFile(new URL(`${d.name}.svg`, OUT), svg(d.width, d.height, d.title, d.body));
}

const sizes = Object.fromEntries(all.map((d) => [`/images/dsa/${d.name}.svg`, [d.width, d.height]]));
await writeFile(
  SIZES,
  `// Generated by scripts/diagrams/build.mjs. Do not edit by hand.\n` +
    `// Width and height of each DSA diagram, so pages can reserve space before it loads.\n\n` +
    `export const diagramSizes: Record<string, [number, number]> = ${JSON.stringify(sizes, null, 2)};\n`,
);

console.log(`Wrote ${all.length} diagrams to public/images/dsa/`);
