#!/usr/bin/env node
// Builds the SVG diagrams used in the notes into public/images/<folder>/ and
// writes their sizes to src/data/diagramSizes.ts, so pages can reserve space
// before an image loads. Run with: npm run diagrams
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { svg } from './svg.mjs';
import { foundations } from './foundations.mjs';
import { structures } from './structures.mjs';
import { trees } from './trees.mjs';
import { graphs } from './graphs.mjs';
import { paradigms } from './paradigms.mjs';
import { javascript } from './javascript.mjs';
import { backend } from './backend.mjs';

const IMAGES = new URL('../../public/images/', import.meta.url);
const SIZES = new URL('../../src/data/diagramSizes.ts', import.meta.url);

// DSA diagrams live in /images/dsa; other modules set their own folder.
const inFolder = (list, folder) => list.map((d) => ({ ...d, folder }));
const all = [
  ...inFolder([...foundations, ...structures, ...trees, ...graphs, ...paradigms], 'dsa'),
  ...inFolder(javascript, 'js'),
  ...inFolder(backend, 'backend'),
];

const seen = new Set();
for (const d of all) {
  const key = `${d.folder}/${d.name}`;
  if (seen.has(key)) throw new Error(`Duplicate diagram: ${key}`);
  seen.add(key);
}

for (const folder of new Set(all.map((d) => d.folder))) {
  const dir = new URL(`${folder}/`, IMAGES);
  await mkdir(dir, { recursive: true });
  for (const file of await readdir(dir)) {
    if (file.endsWith('.svg') && !seen.has(`${folder}/${file.slice(0, -4)}`)) await rm(new URL(file, dir));
  }
}
for (const d of all) {
  await writeFile(new URL(`${d.folder}/${d.name}.svg`, IMAGES), svg(d.width, d.height, d.title, d.body));
}

const sizes = Object.fromEntries(all.map((d) => [`/images/${d.folder}/${d.name}.svg`, [d.width, d.height]]));
await writeFile(
  SIZES,
  `// Generated by scripts/diagrams/build.mjs. Do not edit by hand.\n` +
    `// Width and height of each note diagram, so pages can reserve space before it loads.\n\n` +
    `export const diagramSizes: Record<string, [number, number]> = ${JSON.stringify(sizes, null, 2)};\n`,
);

console.log(`Wrote ${all.length} diagrams to public/images/`);
