// Generated by scripts/diagrams/build.mjs. Do not edit by hand.
// Width and height of each DSA diagram, so pages can reserve space before it loads.

export const diagramSizes: Record<string, [number, number]> = {
  "/images/dsa/complexity-growth.svg": [
    720,
    440
  ],
  "/images/dsa/complexity-nested-loops.svg": [
    760,
    390
  ],
  "/images/dsa/recursion-call-stack.svg": [
    760,
    400
  ],
  "/images/dsa/recursion-fib-tree.svg": [
    720,
    350
  ],
  "/images/dsa/array-indexing.svg": [
    720,
    250
  ],
  "/images/dsa/two-pointers.svg": [
    780,
    350
  ],
  "/images/dsa/sliding-window.svg": [
    780,
    420
  ],
  "/images/dsa/prefix-sum.svg": [
    780,
    320
  ],
  "/images/dsa/binary-search-steps.svg": [
    840,
    420
  ],
  "/images/dsa/binary-search-answer.svg": [
    780,
    270
  ],
  "/images/dsa/merge-sort-tree.svg": [
    760,
    530
  ],
  "/images/dsa/quick-sort-partition.svg": [
    780,
    340
  ],
  "/images/dsa/insertion-sort-steps.svg": [
    760,
    480
  ],
  "/images/dsa/stl-vector-growth.svg": [
    760,
    380
  ],
  "/images/dsa/stl-containers.svg": [
    760,
    790
  ],
  "/images/dsa/linked-list-basic.svg": [
    780,
    220
  ],
  "/images/dsa/linked-list-insert.svg": [
    780,
    330
  ],
  "/images/dsa/linked-list-reverse.svg": [
    820,
    400
  ],
  "/images/dsa/linked-list-cycle.svg": [
    820,
    340
  ],
  "/images/dsa/stack-push-pop.svg": [
    780,
    340
  ],
  "/images/dsa/queue-push-pop.svg": [
    780,
    350
  ],
  "/images/dsa/circular-queue.svg": [
    780,
    420
  ],
  "/images/dsa/monotonic-stack.svg": [
    820,
    380
  ],
  "/images/dsa/hash-chaining.svg": [
    780,
    400
  ],
  "/images/dsa/hash-open-addressing.svg": [
    780,
    300
  ],
  "/images/dsa/heap-tree-array.svg": [
    780,
    440
  ],
  "/images/dsa/heap-insert.svg": [
    820,
    410
  ],
  "/images/dsa/tree-terminology.svg": [
    800,
    430
  ],
  "/images/dsa/tree-types.svg": [
    820,
    300
  ],
  "/images/dsa/tree-traversals.svg": [
    820,
    390
  ],
  "/images/dsa/tree-level-order.svg": [
    820,
    390
  ],
  "/images/dsa/tree-height-depth.svg": [
    800,
    440
  ],
  "/images/dsa/tree-diameter.svg": [
    800,
    430
  ],
  "/images/dsa/tree-views.svg": [
    820,
    430
  ],
  "/images/dsa/tree-lca.svg": [
    800,
    420
  ],
  "/images/dsa/bst-property.svg": [
    820,
    450
  ],
  "/images/dsa/bst-search.svg": [
    820,
    420
  ],
  "/images/dsa/bst-delete-cases.svg": [
    820,
    570
  ],
  "/images/dsa/graph-representation.svg": [
    880,
    380
  ],
  "/images/dsa/graph-bfs.svg": [
    820,
    440
  ],
  "/images/dsa/graph-dfs.svg": [
    820,
    440
  ],
  "/images/dsa/graph-topo-sort.svg": [
    820,
    420
  ],
  "/images/dsa/dijkstra.svg": [
    820,
    420
  ],
  "/images/dsa/mst-kruskal.svg": [
    840,
    420
  ],
  "/images/dsa/greedy-activity-selection.svg": [
    820,
    480
  ],
  "/images/dsa/greedy-merge-intervals.svg": [
    780,
    300
  ],
  "/images/dsa/greedy-min-platforms.svg": [
    820,
    470
  ],
  "/images/dsa/dp-fib-overlap.svg": [
    900,
    440
  ],
  "/images/dsa/dp-climbing-stairs.svg": [
    780,
    290
  ],
  "/images/dsa/dp-lcs-table.svg": [
    820,
    510
  ],
  "/images/dsa/dp-knapsack-table.svg": [
    820,
    420
  ],
  "/images/dsa/backtracking-subsets.svg": [
    880,
    400
  ],
  "/images/dsa/n-queens.svg": [
    780,
    380
  ]
};
